version: '3.8'

services:
  backend:
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.prod
    command: npm start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    ports:
      - "4173:4173"
    env_file:
      - ./frontend/.env.prod