version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # 👈 overridden in prod
    depends_on:
      - backend