version: '3.8'

services:
  backend:
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.local
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host